name: build_docker_and_deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
env:
  DOCKER_USERNAME: liqlos
  DOCKER_IMAGE_NAME: embassy-checker
  DOCKER_IMAGE_TAG: latest
  CONTAINER_NAME: embassy-checker

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --build-arg TELEGRAM_TOKEN="${{secrets.TELEGRAM_TOKEN}}" \
                       --build-arg CHAT_ID="${{secrets.CHAT_ID}}" \
                       --build-arg EMBASSY_EMAIL="${{secrets.EMBASSY_EMAIL}}" \
                       --build-arg EMBASSY_PASSWORD="${{secrets.EMBASSY_PASSWORD}}" \
                       -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
                       
      - name: Push Docker image
        run: docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: docker image prune -f &&
            docker run -d ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME}}:${{ env.DOCKER_IMAGE_TAG}}
